name: Build and Push to S3 
on:
  push:
    branches:
      - dev
  schedule:
    - cron: "30 11 * * 0"
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-south-1 # Replace with your AWS region

      - name: Package and push to S3
        run: |
          # Assuming your project build and packaging steps here
          # Create a timestamped file name using the current date and time
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          ZIP_FILE="MHL_DOS_CATALOGUE_FRONTEND-${TIMESTAMP}.zip"
          zip -r "${ZIP_FILE}" .
          echo  "${ZIP_FILE}"
          aws s3 cp "${ZIP_FILE}" s3://dos2.0-source-code-management/Repo-Backup/MHL_DOS_CATALOGUE_FRONTEND/
